# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [2]:
import numpy as np
a = np.arange(1,11,1)
print(a)
b = np.random.randint(0,50, (3,3))
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[36 38  8]
 [16 11 36]
 [35 27 13]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [3]:
print(a[2:4])

[3 4]



2. Vyberte z pole `a` všechny sudá čísla.


In [4]:
print(a[1::2])

[ 2  4  6  8 10]



3. Obraťte vektor `a` (první prvek se stane posledním).


In [5]:
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1]



5. Vyberte z pole `b` druhý řádek.


In [6]:
print(b)
print("---------------")
print(b[1,:])

[[36 38  8]
 [16 11 36]
 [35 27 13]]
---------------
[16 11 36]



6. Vyberte z pole `b` diagonální prvky.


In [7]:
print(np.diag(b))

[36 11 13]



7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [8]:
print(b)
print("---------------")
b[1,0] = 100
print(b)
print("---------------")


[[36 38  8]
 [16 11 36]
 [35 27 13]]
---------------
[[ 36  38   8]
 [100  11  36]
 [ 35  27  13]]
---------------



8. Vyberte z pole `b` všechny prvky větší než 5.


In [9]:
b1 = b[b>5]
print(b1)

[ 36  38   8 100  11  36  35  27  13]



9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


In [10]:
print(b)
print("--------------")
bmask = b<3
print(bmask)

[[ 36  38   8]
 [100  11  36]
 [ 35  27  13]]
--------------
[[False False False]
 [False False False]
 [False False False]]



10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.




In [11]:
b2 = b[bmask]
print(b2)

[]



## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [12]:
a = np.random.randint(0,100,(10,10))
print(a)

[[60 91 97 42 10 30 24 71 67 30]
 [78 87 25 21 81 35 32 18 29 75]
 [37 24 91 63 88 25 12  2 32 50]
 [60 49 98 18 42  1 18 33 40 69]
 [80 44 35 14 83 91 21 22 84 60]
 [53 75  8  6  4 63 65 16 98 40]
 [52 59  6 50 97 40 39 57 25 82]
 [30 45 52 33 10 35 74 26 20 15]
 [18 36 87 17 22 38  2 17 21 26]
 [21 71 49 16 64 88 24 88 46 11]]



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.


In [13]:
b = a[1,:]
print(b)

[78 87 25 21 81 35 32 18 29 75]



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?


In [14]:
b[0] = 100
print(b)
print("----------------------")
print(a)

[100  87  25  21  81  35  32  18  29  75]
----------------------
[[ 60  91  97  42  10  30  24  71  67  30]
 [100  87  25  21  81  35  32  18  29  75]
 [ 37  24  91  63  88  25  12   2  32  50]
 [ 60  49  98  18  42   1  18  33  40  69]
 [ 80  44  35  14  83  91  21  22  84  60]
 [ 53  75   8   6   4  63  65  16  98  40]
 [ 52  59   6  50  97  40  39  57  25  82]
 [ 30  45  52  33  10  35  74  26  20  15]
 [ 18  36  87  17  22  38   2  17  21  26]
 [ 21  71  49  16  64  88  24  88  46  11]]



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.


In [15]:
c = np.copy(a[1,:])
print(c)

[100  87  25  21  81  35  32  18  29  75]



5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?


In [16]:
c[0] = 200
print(c)
print("----------------------")
print(a)

[200  87  25  21  81  35  32  18  29  75]
----------------------
[[ 60  91  97  42  10  30  24  71  67  30]
 [100  87  25  21  81  35  32  18  29  75]
 [ 37  24  91  63  88  25  12   2  32  50]
 [ 60  49  98  18  42   1  18  33  40  69]
 [ 80  44  35  14  83  91  21  22  84  60]
 [ 53  75   8   6   4  63  65  16  98  40]
 [ 52  59   6  50  97  40  39  57  25  82]
 [ 30  45  52  33  10  35  74  26  20  15]
 [ 18  36  87  17  22  38   2  17  21  26]
 [ 21  71  49  16  64  88  24  88  46  11]]



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.


In [17]:
print("a.base: ", id(a.base))
print("b.base: ", id(b.base))
print("c.base: ", id(c.base))
print(b is c.base)

a.base:  94846679282656
b.base:  140629497915760
c.base:  94846679282656
False



7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.


In [18]:
d = np.copy(np.diag(a))
print(d)

[60 87 91 18 83 63 39 26 21 11]



8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



In [19]:
print(d.flags)
d[0] = 300
print(a)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[[ 60  91  97  42  10  30  24  71  67  30]
 [100  87  25  21  81  35  32  18  29  75]
 [ 37  24  91  63  88  25  12   2  32  50]
 [ 60  49  98  18  42   1  18  33  40  69]
 [ 80  44  35  14  83  91  21  22  84  60]
 [ 53  75   8   6   4  63  65  16  98  40]
 [ 52  59   6  50  97  40  39  57  25  82]
 [ 30  45  52  33  10  35  74  26  20  15]
 [ 18  36  87  17  22  38   2  17  21  26]
 [ 21  71  49  16  64  88  24  88  46  11]]


9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.


In [20]:
e = a.T
print(a)
print("-----------------")
print(e)
print("-----------------")
print(e.flags)

[[ 60  91  97  42  10  30  24  71  67  30]
 [100  87  25  21  81  35  32  18  29  75]
 [ 37  24  91  63  88  25  12   2  32  50]
 [ 60  49  98  18  42   1  18  33  40  69]
 [ 80  44  35  14  83  91  21  22  84  60]
 [ 53  75   8   6   4  63  65  16  98  40]
 [ 52  59   6  50  97  40  39  57  25  82]
 [ 30  45  52  33  10  35  74  26  20  15]
 [ 18  36  87  17  22  38   2  17  21  26]
 [ 21  71  49  16  64  88  24  88  46  11]]
-----------------
[[ 60 100  37  60  80  53  52  30  18  21]
 [ 91  87  24  49  44  75  59  45  36  71]
 [ 97  25  91  98  35   8   6  52  87  49]
 [ 42  21  63  18  14   6  50  33  17  16]
 [ 10  81  88  42  83   4  97  10  22  64]
 [ 30  35  25   1  91  63  40  35  38  88]
 [ 24  32  12  18  21  65  39  74   2  24]
 [ 71  18   2  33  22  16  57  26  17  88]
 [ 67  29  32  40  84  98  25  20  21  46]
 [ 30  75  50  69  60  40  82  15  26  11]]
-----------------
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  W



## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [21]:
A = np.random.randint(0,10,(5,3))
B = np.random.randint(0,10,(3,2))
print("-----------------------")
print(A)
print("-----------------------")
print(B)
C = A@B
print("-----------------------")
print(C)

-----------------------
[[6 0 5]
 [0 8 4]
 [6 6 8]
 [3 2 8]
 [8 4 9]]
-----------------------
[[5 6]
 [7 2]
 [2 0]]
-----------------------
[[40 36]
 [64 16]
 [88 48]
 [45 22]
 [86 56]]


2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


In [22]:
def polCoor(x,y):
    absV =np.sqrt(x*x+y*y)
    phi = np.arctan2(y,x)
    return absV,phi

polCoor_v = np.vectorize(polCoor)

Cart = np.random.rand(10,2)
x,y = Cart[:,0], Cart[:,1]

Pol = np.zeros((10,2))
Pol[:,0], Pol[:,1] = polCoor_v(x,y)
print(Cart)
print("-------------------")
print(Pol)

[[0.25577087 0.98483416]
 [0.83887074 0.81073112]
 [0.24123351 0.81304609]
 [0.96081827 0.67599052]
 [0.33980838 0.27264528]
 [0.86967116 0.55203224]
 [0.27290006 0.21640475]
 [0.02835515 0.20231281]
 [0.81494329 0.19463863]
 [0.68139015 0.05008172]]
-------------------
[[1.01750531 1.31670032]
 [1.16661437 0.76834139]
 [0.84807874 1.2823667 ]
 [1.17479144 0.61310929]
 [0.43566637 0.67617227]
 [1.03008132 0.56558679]
 [0.34828933 0.6704468 ]
 [0.2042902  1.4315484 ]
 [0.8378644  0.23444505]
 [0.68322816 0.07336741]]


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


In [30]:
x = np.random.randint(1,100,5)
y = np.random.randint(1,100,5)

xIndx = np.array( [[x[m] for n in range(x.shape[0])] for m in range(y.shape[0])] )
yIndx = np.array( [ [y[n] for n in range(x.shape[0])] for m in range(y.shape[0])] )

C = 1/(xIndx-yIndx)
print(C)


[78 99  7 35 76]
--------------------
[89 47 89 65 20]
--------------------
[[-0.09090909  0.03225806 -0.09090909  0.07692308  0.01724138]
 [ 0.1         0.01923077  0.1         0.02941176  0.01265823]
 [-0.01219512 -0.025      -0.01219512 -0.01724138 -0.07692308]
 [-0.01851852 -0.08333333 -0.01851852 -0.03333333  0.06666667]
 [-0.07692308  0.03448276 -0.07692308  0.09090909  0.01785714]]


4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


In [73]:
coor = np.random.randint(0,10,(5,2))
print(coor)
print("--------------------")

def dist(x,y):
    return np.sqrt(x*x+y*y)

dist_v = np.vectorize(dist)

distList = dist_v(coor[:,0], coor[:,1])
print(distList)


[[3 7]
 [6 7]
 [1 5]
 [7 6]
 [5 7]]
--------------------
[7.61577311 9.21954446 5.09901951 9.21954446 8.60232527]


5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


In [76]:
A = np.random.randint(1,100,(10,10))
B = np.random.randint(1,100,(10,10))
ABT = (A@B).T
ATBT = (B.T)@(A.T)
if(ABT == ATBT).all():
    print(True)


True


6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


In [83]:
u = np.random.randint(1,100,5)
v = np.random.randint(1,100,5) 
ur = u[:,np.newaxis]
vc = v[np.newaxis,:]
A = ur@vc
B = np.outer(u,v)
print(A)
print("-------------------")
print(B)


[[2409 1752 6789  365 6643]
 [ 825  600 2325  125 2275]
 [  66   48  186   10  182]
 [1419 1032 3999  215 3913]
 [ 363  264 1023   55 1001]]
-------------------
[[2409 1752 6789  365 6643]
 [ 825  600 2325  125 2275]
 [  66   48  186   10  182]
 [1419 1032 3999  215 3913]
 [ 363  264 1023   55 1001]]


7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?


In [31]:
u = np.arange(0,30,1)
print(u)
u =  u.reshape((5,6))
print(u)
print(np.linalg.matrix_rank(u))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
2



## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


In [93]:
data = np.random.randint(1,100,(10,10))
print(data)
print(data.min())
print(data.max())

[[46 61 14 68  1 19 60 59 78 37]
 [64  2 42 60 11 78 77 27 52 16]
 [30 44 89 35 92 50 17 42 29  8]
 [18 63 42 86 98 21 62 65 94 16]
 [39 64 25 58  2  8 64 64 31 65]
 [84 53 59 86 35 49 62 99 46 21]
 [42  2 27 72 83 69 30 23 87  7]
 [57  6 28 42 66 32  7 87 71 85]
 [52  5 12 18 98 94 97 25 29 35]
 [73 38 88 31  6 78 81  2 90 39]]
1
99


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



In [96]:
vec = np.random.randint(1,100, 30)
print(vec)
print(np.std(data))

[68 31 77 88 20 20 63 85 48 16 93 10 90 54 30 54 55  7 42 48 63 34 42 94
 35 17 47  4 38 36]
28.552581319383364


3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



In [36]:
b = np.arange(1,11,1)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```



6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 



7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?




8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 

